# Smart Flashcards — single production container.
# Stage 1 builds the React frontend, stage 2 resolves Python deps into a venv
# (poetry never ships in the runtime image), stage 3 runs FastAPI serving both
# the JSON API (/api/*) and the built SPA from one origin.
# See docs/DEPLOY.md for the Railway walkthrough.

# ---- Stage 1: frontend build -------------------------------------------------
FROM node:22-alpine AS frontend
WORKDIR /build
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

# ---- Stage 2: python dependency resolution ------------------------------------
FROM python:3.12-slim AS deps
ENV PIP_NO_CACHE_DIR=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true
WORKDIR /app
# poetry 2.x matches the committed poetry.lock (generated by 2.1)
RUN pip install "poetry>=2.1,<3"
COPY backend/pyproject.toml backend/poetry.lock ./
RUN poetry install --only main --no-root --no-interaction

# ---- Stage 3: runtime ----------------------------------------------------------
FROM python:3.12-slim AS runtime
ENV PYTHONUNBUFFERED=1 \
    PATH="/app/.venv/bin:$PATH"
WORKDIR /app

COPY --from=deps /app/.venv ./.venv
COPY backend/app ./app
COPY --from=frontend /build/dist ./static

# Serve the SPA from this image; persist user data on the volume mounted at /data.
ENV STATIC_DIR=/app/static \
    DATA_DIR=/data

EXPOSE 8000
# PORT is set explicitly on Railway (docs/DEPLOY.md); default to 8000 for local runs.
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
