# Smart Flashcards — single production container.
# Stage 1 builds the React frontend; stage 2 runs FastAPI, which serves both the
# JSON API (/api/*) and the built SPA (same origin, so no CORS/proxy config needed).
# See docs/DEPLOY.md for the Railway walkthrough.

# ---- Stage 1: frontend build -------------------------------------------------
FROM node:22-alpine AS frontend
WORKDIR /build
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

# ---- Stage 2: backend runtime ------------------------------------------------
FROM python:3.12-slim AS runtime
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

# poetry 2.x matches the committed poetry.lock (generated by 2.1)
RUN pip install "poetry>=2.1,<3"
COPY backend/pyproject.toml backend/poetry.lock ./
RUN poetry install --only main --no-root --no-interaction

COPY backend/app ./app
COPY --from=frontend /build/dist ./static

# Serve the SPA from this image; persist user data on the volume mounted at /data.
ENV STATIC_DIR=/app/static \
    DATA_DIR=/data

EXPOSE 8000
# Railway injects PORT; default to 8000 for local `docker run`.
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}"]
